# Introduction

Working with numbers is central to almost all scientific and engineering computations. 
The topic is so important that there are many dedicated libraries to help implement efficient numerical
computations. There are even languages that are specifically designed for numerical computation, such as Fortran
and MATLAB.

NumPy (http://www.numpy.org/) is the most widely used Python library for numerical computations.  It provides an extensive range of data structures and functions for numerical
computation. In this notebook we will explore just some of the functionality.
You will be seeing NumPy in other courses. NumPy can perform many of the operations that you will learn
during the mathematics courses.

Another library, which largely builds on NumPy and provides additional functionality, is SciPy (https://www.scipy.org/). SciPy provides some  more specialised data structures and functions over NumPy. 
If you are familiar with MATLAB, NumPy and SciPy provide much of what is available in MATLAB.

NumPy is a large and extensive library and this activity is just a very brief introduction.
To discover how to perform operations with NumPy your best resources are search engines, such as http://stackoverflow.com/.


## Objectives

- Introduction to 1D and 2D arrays (vector and matrices) 
- Manipulating arrays (indexing, slicing, etc)
- Apply elementary numerical operations
- Demonstrate efficiency differences between vectorised and non-vectorised functions

# Importing the NumPy module

To make NumPy available in our programs, we need to import the module. It has become an informal custom to import NumPy using the shortcut '`np`': 

In [1]:
import numpy as np

# Numerical arrays

We have already seen Python 'lists', which hold 'arrays' of data.  We can access the elements of a list using an index because the entries are stored in order. Python lists are very flexible and can hold mixed data types, e.g. combinations op floats and strings, or even lists of lists of lists . . .

The flexibility of Python lists comes at the expense of performance. Many science, engineering and mathematics problems involve very large problems with operations on numbers, and computational speed is important for large problems. To serve this need, we normally use specialised functions and data structures for numerical computation, and in particular for arrays of numbers. Some of the flexibility of lists is traded for performance.

## One-dimensional arrays

A one-dimensional array is a collection of numbers which we can access by index (it preserves order).

### Creating arrays and indexing 

To create a NumPy array of length 10 and initially filled with zeros:

In [2]:
x = np.zeros(10)

print(x)
print(type(x))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
<class 'numpy.ndarray'>


The default type of a NumPy array is `float`. The type can be checked with

In [3]:
print(x.dtype)

float64


You cannot, for example, add a `string` to a `numpy.ndarray`. All entries in the array have the same type.

We can check the length of an array using `len`, which gives the number of entries in the array:

In [4]:
print(len(x))

10


A better way to check the length is to use `x.shape`, which returns a tuple with the dimensions of the array:

In [5]:
print(x.shape)

(10,)


`shape` tells us the size of the array in *each* direction. We will see two-dimensional arrays shortly (matrices), which have a size in each direction.

We can change the entries of an array using indexing,

In [6]:
print(x)

x[0] = 10.0
x[3] = -4.3
x[9] = 1.0

print(x)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 10.    0.    0.   -4.3   0.    0.    0.    0.    0.    1. ]


Remember that indexing starts from zero!

There are other ways to create arrays, such as an array of 'ones':

In [7]:
y = np.ones(5)
print(y)

[ 1.  1.  1.  1.  1.]


an array of random values:

In [8]:
y = np.random.rand(6)
print(y)

[ 0.00842384  0.88041776  0.43655009  0.8954834   0.01341437  0.07293609]


or a NumPy array from a Python list:

In [9]:
x = [4.0, 8.0, 9.0, 11.0, -2.0]
y = np.array(x)
print(y)

[  4.   8.   9.  11.  -2.]


Two more methods for creating arrays which we will use in later notebooks are:

- `numpy.arange`; and 
- `numpy.linspace`. 

They are particularly useful for plotting functions.
The function `arange` creates an array with equally spaced values. It is similar in some cases to `range`, which we have seen earlier. To create the array `[0 1 2 3 4 5]` using `arange`:

In [10]:
x = np.arange(6)
print(x)
print(type(x))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


Note that '6' is not included. We can change the start value, e.g.:

In [11]:
x = np.arange(2, 6)
print(x)

[2 3 4 5]


The function `linspace` creates an array with prescribed start and end values (both are included), and a prescribed number on values, all equally spaced:

In [12]:
x = np.linspace(0, 100, 6)
print(x)

[   0.   20.   40.   60.   80.  100.]


The `linspace` function is used extensively for plotting, as we will see in the next notebook.

### Array arithmetic and functions

NumPy arrays support common arithmetic operations, such as addition of two arrays

In [13]:
x = np.array([1.0, 0.2, 1.2])
y = np.array([2.0, 0.1, 2.1])
print(x)
print(y)

# Sum x and y
z = x + y
print(z)

[ 1.   0.2  1.2]
[ 2.   0.1  2.1]
[ 3.   0.3  3.3]


and multiplication of components by a scalar,

In [14]:
z = 10.0*x
print(z)

[ 10.   2.  12.]


and raising components to a power:

In [15]:
x = np.array([2, 3, 4])
print(x**2)

[ 4  9 16]


We can also apply functions to the components of an array:

In [16]:
# Create an array [0, π/2, π, 3π/2]
x = np.array([0.0, np.pi/2, np.pi, 3*np.pi/2])
print(x)

# Compute sine of each entry
y = np.sin(x)
print(y)

[ 0.          1.57079633  3.14159265  4.71238898]
[  0.00000000e+00   1.00000000e+00   1.22464680e-16  -1.00000000e+00]


The above has computed the sine of each entry in the array `x`.

Note that the function `np.sin` is used, and not `math.sin` (which was used in previous notebooks). The reason is that `np.sin` is more general -  it can act on lists/arrays of values rather than on just one value. We will apply functions to arrays in the next notebook to plot functions.

We could have computed the sine of each array entry using `for` loops:

In [17]:
y = np.zeros(len(x))
for i in range(len(x)):
    y[i] = np.sin(x[i])

print(y)

[  0.00000000e+00   1.00000000e+00   1.22464680e-16  -1.00000000e+00]


but the program becomes longer and harder to read. Additionally, in many cases it will be much slower. 
You might see manipulation of arrays without indexing referred to as 'vectorisation'. When possible, vectorisation is a good thing to do. We compare the performance of indexing versus vectorisation below.

### Performance example: computing the norm of a long vector

The norm of a vector $x$ is given by: 

$$
\| x \| = \sqrt{\sum_{i=0}^{n-1} x_{i} x_{i}}
$$

where $x_{i}$ is the $i$th entry of $x$. It is the dot product of a vector with itself, 
followed by taking the square root.
To compute the norm, we could loop/iterate over the entries of the vector and sum the square of each entry, and then take the square root of the result.

We will evaluate the norm using two methods for computing the norm on an array of length 10 million to compare their performance. We first create a vector with 10 million random entries, using NumPy:

In [18]:
# Create a NumPy array with 10 million random values
x = np.random.rand(10000000)
print(type(x))

<class 'numpy.ndarray'>


We now time how long it takes to compute the norm of the vector using the NumPy function '`numpy.dot`'. We use the Jupyter 'magic command' [`%time`](Notebook%20tips.ipynb#Simple-timing) to time the operation: 

In [19]:
%time norm = np.sqrt(np.dot(x, x))
print(norm)

CPU times: user 8 ms, sys: 0 ns, total: 8 ms
Wall time: 5.47 ms
1826.04154125


The time output of interest is '`Wall time`'.

We now perform the same operation with our own function for computing the norm:

In [20]:
def compute_norm(x):
    norm = 0.0
    for xi in x:
        norm += xi*xi
    return np.sqrt(norm)

%time norm =compute_norm(x)
print(norm)

CPU times: user 1.13 s, sys: 0 ns, total: 1.13 s
Wall time: 1.12 s
1826.04154125


You should see that the two approaches give the same result, but the 
NumPy function is more than 100 times faster, and possibly more than 100,000 times faster!

The message is that specialised functions and data structures for numerical computations can be many orders of magnitude faster than your own general implementations. On top of that, the specialised functions are much less 
likely to have bugs!

## Two-dimensional arrays

Two-dimensional arrays are very useful for arranging data in many engineering applications and for performing mathematical operations. Commonly, 2D arrays are used to represents matrices. To create the matrix

$$
A = 
\begin{bmatrix} 
2.2 & 3.7 & 9.1\\ 
-4 & 3.1 & 1.3
\end{bmatrix} 
$$

we use:

In [21]:
A = np.array([[2.2, 3.7, 9.1], [-4.0, 3.1, 1.3]])
print(A)

[[ 2.2  3.7  9.1]
 [-4.   3.1  1.3]]


If we check the length of `A`:

In [22]:
print(len(A))

2


it reports the number of rows. To get the shape of the array, we use:

In [23]:
print(A.shape)

(2, 3)


which reports 2 rows and 3 columns (stored using a tuple). To get the number of rows and the number of columns,

In [24]:
num_rows = A.shape[0]
num_cols = A.shape[1]
print("Number of rows is {}, number of columns is {}.".format(num_rows, num_cols))

Number of rows is 2, number of columns is 3.


We can 'index' into a 2D array using two indices, the first for the row index and the second for the column index:

In [25]:
A02 = A[0, 2]
print(A02)

9.1


With `A[1]`, we will get the second row:

In [26]:
print(A[1])

[-4.   3.1  1.3]


We can iterate over the entries of `A` by iterating over the rows, and then the entry in each row:

In [27]:
for row in A:
    print("-----")
    for c in row:
        print(c)

-----
2.2
3.7
9.1
-----
-4.0
3.1
1.3


> **Warning:** NumPy has a `numpy.matrix` data structure. Its use is not recommended as it behaves inconsistently in some cases.

### 2D array (matrix) operations

For those who have seen matrices previously, the operations in this section will be familiar. For those who have not encountered matrices you might want to revisit this section once matrices have been covered in the mathematics lectures.

#### Matrix-vector and matrix-matrix multiplication

We will consider the matrix $A$:

$$
A  = 
\begin{bmatrix}
3.4 & 2.6 \\
2.1 & 4.5
\end{bmatrix}
$$

and the vector $x$:

$$
x  = 
\begin{bmatrix}
0.2 \\ -1.1
\end{bmatrix}
$$

In [28]:
A = np.array([[3.4, 2.6], [2.1, 4.5]])
print("Matrix A:\n {}".format(A))

x = np.array([0.2, -1.1])
print("Vector x:\n {}".format(x))

Matrix A:
 [[ 3.4  2.6]
 [ 2.1  4.5]]
Vector x:
 [ 0.2 -1.1]


We can compute the matrix-vector product $y = Ax$ by:

In [29]:
y = A.dot(x)
print(y)

[-2.18 -4.53]


Matrix-matrix multiplication is performed similarly. Computing $C = AB$, where $A$, $B$, and $C$ are all matrices:

In [30]:
B = np.array([[1.3, 0], [0, 2.0]])

C = A.dot(B)
print(C)

[[ 4.42  5.2 ]
 [ 2.73  9.  ]]


The inverse of a matrix ($A^{-1}$) and the determinant ($\det(A)$) can be computed using functions in the NumPy submodule `linalg`:

In [31]:
Ainv = np.linalg.inv(A)
print("Inverse of A:\n {}".format(Ainv))

Adet = np.linalg.det(A)
print("Determinant of A: {}".format(Adet))

Inverse of A:
 [[ 0.45731707 -0.26422764]
 [-0.21341463  0.34552846]]
Determinant of A: 9.839999999999998


> NumPy is large library, so it uses sub-modules to arrange functionality.

A very common matrix is the *identity matrix* $I$. We can create a $4 \times 4$ identity matrix using:

In [32]:
I = np.eye(4)
print(I)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


# Array slicing

When working with arrays, it is often useful to extract subsets of an array. We might want just the first 3 entries of a long array, or we might want the second column of a 2D array (matrix). These operations are known as *array slicing* (https://en.wikipedia.org/wiki/Array_slicing).

We will explore slicing through examples. We start by creating an array filled with random values:

In [33]:
x = np.random.rand(5)
print(x)

[ 0.72506169  0.0303733   0.03342896  0.98150279  0.88843666]


Below are some slicing operations:

In [34]:
# Using ':' implies the whole range of indices, i.e. from 0 -> (length-1)
y = x[:]
print("Slice using '[:]' {}".format(y))

# Using '1:3' implies indices 1 -> 3 (not including 3)
y = x[1:3]
print("Slice using '[1:3]': {}".format(y))

# Using '2:-1' implies indices 2 -> second-from-last
y = x[2:-1]
print("Slice using '[2:-1]': {}".format(y))

Slice using '[:]' [ 0.72506169  0.0303733   0.03342896  0.98150279  0.88843666]
Slice using '[1:3]': [ 0.0303733   0.03342896]
Slice using '[2:-1]': [ 0.03342896  0.98150279]


Note that the index `-1` corresponds to the last entry in the array, `-2` the second last entry, etc.

If we want a slice to run from the start of an array, or to the end of an array, we do: 

In [35]:
# Using ':3' implies start -> 3 (not including 3)
y = x[:3]
print("Slice using '[:3]': {}".format(y))

# Using '4:' implies 4 -> end
y = x[4:]
print("Slice using '[4:]': {}".format(y))

# Using ':' implies start -> end
y = x[:]
print("Slice using '[:]': {}".format(y))

Slice using '[:3]': [ 0.72506169  0.0303733   0.03342896]
Slice using '[4:]': [ 0.88843666]
Slice using '[:]': [ 0.72506169  0.0303733   0.03342896  0.98150279  0.88843666]


Slicing can be applied to 2D arrays:

In [36]:
B = np.array([[1.3, 0], [0, 2.0]])
print(B)

# Extract second row
r = B[1, :]
print(r)

[[ 1.3  0. ]
 [ 0.   2. ]]
[ 0.  2.]


There is more to array slicing syntax, for example it is possible to extract every 3rd entry. If you need to extract a sub-array, check first if you can do it using the compact array slicing syntax.

# Exercises

## Exercise 07.1 (indexing and timing)

Create two very long NumPy arrays `x` and `y` and sum the arrays using:

1. The NumPy addition syntax, `z = x + y`; and
2. A `for` loop that computes the sum entry-by-entry

Compare the time required for the two approaches for vectors of different lengths. The values of the array entries are not important for this test.

*Hint:* To loop over an array using indices, try a construction like:
```python
x = np.ones(100)
y = np.ones(len(x))
for i in range(len(x)):
    print(x[i]*y[i])
```

In [22]:
import numpy as np
import timeit

x = np.arange(1,98)
y = np.ones(len(x))

#1
z = x + y
#print(z)
%time norm = (x+y)
print(norm)
#2
#print([x + y for x, y in zip(x, y)])
% time norm = [x + y for x, y in zip(x, y)]
print(norm)


CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 34.1 µs
[  2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.  16.
  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.  29.  30.  31.
  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.  43.  44.  45.  46.
  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.  57.  58.  59.  60.  61.
  62.  63.  64.  65.  66.  67.  68.  69.  70.  71.  72.  73.  74.  75.  76.
  77.  78.  79.  80.  81.  82.  83.  84.  85.  86.  87.  88.  89.  90.  91.
  92.  93.  94.  95.  96.  97.  98.]
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 313 µs
[2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.

## Exercise 07.2 (member functions and slicing)

Anonymised scores (out of 60) for an examination are stored in a NumPy array. Write:

1. A function that takes a NumPy array of the raw scores and returns the scores as a percentage sorted from 
   lowest to highest (try using `scores.sort()`, where `scores` is a NumPy array holding the scores).
1. A function that returns the maximum, minimum and mean of the raw scores as a dictionary with the 
   keys '`min`', '`max`' and '`mean`'. Use the NumPy array functions `min()`, `max()` and `mean()` to do the 
   computation, e.g. `max = scores.max()`.
1. Modify your function for the min, max and mean to optionally exclude the highest and lowest scores from the 
   computation of the min, max and mean. *Hint:* sort the array of scores and use array slicing to exclude
   the first and the last entries.

Use the scores 
```python
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
```
to test your functions.

In [4]:
import numpy as np
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])

#1
def scores_pct(scores):
    scores.sort()
    scores = (100/60) * scores
    return scores

print(scores_pct(scores))

#2
def scores_dict(scores, exclude = False):
    scores.sort()
    keys = ['min', 'max', 'mean']
    if not exclude:
        v = [scores.min(), scores.max(), scores.mean()]
    else:
        v = [scores[1:-1].min(), scores[1:-1].max(), scores[1:-1].mean()]
    d = dict(zip(keys, v))
    return d

print(scores_dict(scores))
print(scores_dict(scores, True))


[ 13.          40.          58.33333333  70.          96.66666667]
{'min': 7.7999999999999998, 'max': 58.0, 'mean': 33.359999999999999}
{'min': 24.0, 'max': 42.0, 'mean': 33.666666666666664}


## Exercise 07.3 (slicing)

For the two-dimensional array

In [37]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
print(A)

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]


use array slicing to

1. Extract the third column as a 1D array
2. Extract the first two rows as a 2D sub-array
3. Extract the bottom-right $2 \times 2$ block as a 2D sub-array
4. Sum the last column

Print the results to the screen to check. Try to use array slicing such that your code would still work if the dimensions of `A` were enlarged.

Also, compute the tranpose of `A` (search online to find the function/syntax to do this).

In [6]:
import numpy as np
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
#print(A)

#1 Extract 3rd column
b = A[:, 2]
print("\n Extract 3rd column:", "\n",b)

#2 Extract first 2 rows
c = A[[0,1],:]
print("\n Extract first 2 rows:", "\n", c)

#3 Extract bottom-right 2x2 block
d = A[[2,3],2:]
print("\n Extract bottom-right 2x2 block:", "\n", d)

#4 Sum the last column
e = sum(A[:,3])
print("\n Sum of last column:", e)

#transpose array
f = A.T
print("\n Transpose array A:", "\n", f)


 Extract 3rd column: 
 [  -2.43   54.7     3.64 -113.2 ]

 Extract first 2 rows: 
 [[  4.     7.    -2.43  67.1 ]
 [ -4.    64.    54.7   -3.33]]

 Extract bottom-right 2x2 block: 
 [[   3.64    4.11]
 [-113.2   323.22]]

 Sum of last column: 391.1

 Transpose array A: 
 [[   4.     -4.      2.43    1.2 ]
 [   7.     64.     23.2     2.5 ]
 [  -2.43   54.7     3.64 -113.2 ]
 [  67.1    -3.33    4.11  323.22]]


## Exercise 07.4 (optional extension)

In a previous exercise you implemented the bisection algorithm to find approximate roots of a mathematical function. Use the SciPy bisection function `optimize.bisect` (http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.optimize.bisect.html) to find roots of the mathematical function that was used in the previous exercise. Compare the results computed by SciPy and your program from the earlier exercise, and compare the computational time (using `%time`).